name: Conviso SCA
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]
 workflow_dispatch:
jobs:
 conviso-sca:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.CONVISO_API_KEY}}
       FLOW_PROJECT_CODE: ${{secrets.CONVISO_PROJECT_CODE}}

   steps:
   - uses: actions/checkout@v2

   - name: Run SCA
     run: conviso sca run
